name: Push Code to Backend Branch

on:
  push:
    paths:
      - backend/**

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Backend Code
        uses: s0/git-publish-subdir-action@develop
        with:
          repo: self
          branch: backend
          folder: backend
          token: ${{ secrets.GITHUB_TOKEN }}
