name: Push Code to Frontend Branch

on:
  push:
    paths:
      - frontend/**

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Deploy Frontend Code
      - name: Deploy Frontend Code
        uses: s0/git-publish-subdir-action@develop
        with:
          repo: self
          branch: frontend
          folder: frontend
          token: ${{ secrets.GITHUB_TOKEN }}
